title: Streamdata Gallery Azure DevTest Labs
url: azure-devtest-labs.streamdata.gallery
tag: Azure DevTest Labs
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: azure-devtest-labs
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
